language: node_js
node_js:
- '0.10'
services:
- mongodb
deploy:
  provider: modulus
  api_key:
    secure: eynsxfRNIGTfoQraQ/GtlWjODu0X6vvb8oavWDC0qO/UNsbudAWVp76U2CPtVm3DgvjEkCt95L7rDeOZZJf47H6M3mST6n9p7YFABswUXJuZObAg/loRODZHf0fVu1rxIDes6I3N7SU2NhG93h20tYxkq9YGg9GwHVH9zN8uRGs=
  project_name: Project Hydra
  on:
    all_branches: true
  skip_cleanup: true